export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Austria",
  "Switzerland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Portugal",
  "Greece",
  "Ireland",
  "Luxembourg",
  "Australia",
  "New Zealand",
  "Japan",
  "South Korea",
  "Singapore",
] as const

export type Country = (typeof COUNTRIES)[number]
